name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chamfort/rabbitmq-consumer:${{ steps.date.outputs.date }}
     
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Publish Image to DockerHub
      run: docker push ${{secrets.DOCKERHUB_USERNAME }}/rabbitmq-consumer:${{ steps.date.outputs.date }}


